import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { Providers } from "@/providers/nextuiProvider";
import Navigation from "@/components/navbar";

import { Montserrat } from 'next/font/google'

const fontWeights:any = ['400', '500', '600', '700', '800']

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700', '800'] ,
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className } bg-zinc-50`}>
        {/* <Providers> */}
          <Navigation/>
          {children}
        {/* </Providers> */}
        </body>
    </html>
  );
}
